name: 🚀 Deploy on srv1.lambdainfotech.com

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: 🎉 Deployment Flow
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          known_hosts: 'carttelo_deploy'

      - name: 🚚 Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.STAGING_SSH_PORT }} -H ${{ secrets.STAGING_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Run Deployment Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SSH_HOST }}
          username: ${{ secrets.STAGING_SSH_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          command_timeout: 30m
          script: |
            cd /www/wwwroot/carttelo
            git stash
            git pull origin main
            COMPOSER_ALLOW_SUPERUSER=1 composer install --no-interaction
            npm run build
            chown -R www:www /www/wwwroot/carttelo
            find . -type d -exec chmod 755 {} \; && find . -type f -exec chmod 644 {} \;
            chmod -R 775 /www/wwwroot/carttelo/storage /www/wwwroot/carttelo/bootstrap/cache
